name: Bug Report / Feature Request
description: Report a bug or suggest an improvement
title: "[Bug/Feature] "
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug Report
        - Feature Request
        - Question
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug or feature request
      placeholder: "What's happening? What would you like to see?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context (optional)
      description: Any other relevant information
    validations:
      required: false
